# Generated by Django 4.2.5 on 2023-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_personalinfo_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
